### ISSUE TITLE
Sofia Dacharry

### ISSUE THREAD

**Issue by sofiadacharry** [umiami-web-design/project-css#17]
file:///Users/sofiadacharry/Documents/GitHub/sofiadacharry.github.io/resume.html

**Comment by ebrown15** [comment]
I have no access to files with this URL. When I checked your repo (https://github.com/sofiadacharry/sofiadacharry.github.io), you hadn't uploaded your work anyway.

**Comment by sofiadacharry** [comment]
Hi Erin,

I uploaded my files to Github like I’ve done with the last two assignments. The link to my website that I submitted showed my resume was live. I’m at my internship right now but I’m going to check my laptop when I get out at 6pm. 

Best,
Sofia
